export const CITY_DETAILS_REQUEST = "CITY_DETAILS_REQUEST";
export const CITY_DETAILS_SUCCESS = "CITY_DETAILS_SUCCESS";
export const CITY_DETAILS_FAIL = "CITY_DETAILS_FAIL";

export const ADD_CITY_REQUEST = "ADD_CITY_REQUEST";
export const ADD_CITY_SUCCESS = "ADD_CITY_SUCCESS";
export const ADD_CITY_FAIL = "ADD_CITY_FAIL";
export const ADD_CITY_RESET = "ADD_CITY_RESET";


export const UPDATE_CITY_REQUEST = "UPDATE_CITY_REQUEST";
export const UPDATE_CITY_SUCCESS = "UPDATE_CITY_SUCCESS";
export const UPDATE_CITY_FAIL = "UPDATE_CITY_FAIL";
export const UPDATE_CITY_RESET = "UPDATE_CITY_RESET";

export const DELETE_CITY_REQUEST = "DELETE_CITY_REQUEST";
export const DELETE_CITY_SUCCESS = "DELETE_CITY_SUCCESS";
export const DELETE_CITY_FAIL = "DELETE_CITY_FAIL";
export const DELETE_CITY_RESET = "DELETE_CITY_RESET";




export const CLEAR_ERRORS = "CLEAR_ERRORS";
