export const EVENT_DETAILS_REQUEST = "EVENT_DETAILS_REQUEST";
export const EVENT_DETAILS_SUCCESS = "EVENT_DETAILS_SUCCESS";
export const EVENT_DETAILS_FAIL = "EVENT_DETAILS_FAIL";

export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAIL = "ADD_EVENT_FAIL";
export const ADD_EVENT_RESET = "ADD_EVENT_RESET";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";
export const UPDATE_EVENT_RESET = "UPDATE_EVENT_RESET";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";
export const DELETE_EVENT_RESET = "DELETE_EVENT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
