export const HONEYMOON_DETAILS_REQUEST = "HONEYMOON_DETAILS_REQUEST";
export const HONEYMOON_DETAILS_SUCCESS = "HONEYMOON_DETAILS_SUCCESS";
export const HONEYMOON_DETAILS_FAIL = "HONEYMOON_DETAILS_FAIL";

export const SINGLE_HONEYMOON_REQUEST = "SINGLE_HONEYMOON_REQUEST";
export const SINGLE_HONEYMOON_SUCCESS = "SINGLE_HONEYMOON_SUCCESS";
export const SINGLE_HONEYMOON_FAIL = "SINGLE_HONEYMOON_FAIL";

export const ADD_HONEYMOON_REQUEST = "ADD_HONEYMOON_REQUEST";
export const ADD_HONEYMOON_SUCCESS = "ADD_HONEYMOON_SUCCESS";
export const ADD_HONEYMOON_FAIL = "ADD_HONEYMOON_FAIL";
export const ADD_HONEYMOON_RESET = "ADD_HONEYMOON_RESET";

export const UPDATE_HONEYMOON_REQUEST = "UPDATE_HONEYMOON_REQUEST";
export const UPDATE_HONEYMOON_SUCCESS = "UPDATE_HONEYMOON_SUCCESS";
export const UPDATE_HONEYMOON_FAIL = "UPDATE_HONEYMOON_FAIL";
export const UPDATE_HONEYMOON_RESET = "UPDATE_HONEYMOON_RESET";

export const DELETE_HONEYMOON_REQUEST = "DELETE_HONEYMOON_REQUEST";
export const DELETE_HONEYMOON_SUCCESS = "DELETE_HONEYMOON_SUCCESS";
export const DELETE_HONEYMOON_FAIL = "DELETE_HONEYMOON_FAIL";
export const DELETE_HONEYMOON_RESET = "DELETE_HONEYMOON_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
