export const LOVESTORY_DETAILS_REQUEST = "LOVESTORY_DETAILS_REQUEST";
export const LOVESTORY_DETAILS_SUCCESS = "LOVESTORY_DETAILS_SUCCESS";
export const LOVESTORY_DETAILS_FAIL = "LOVESTORY_DETAILS_FAIL";

export const APPROVED_LOVESTORY_REQUEST = "APPROVED_LOVESTORY_REQUEST";
export const APPROVED_LOVESTORY_SUCCESS = "APPROVED_LOVESTORY_SUCCESS";
export const APPROVED_LOVESTORY_FAIL = "APPROVED_LOVESTORY_FAIL";

export const ADD_LOVESTORY_REQUEST = "ADD_LOVESTORY_REQUEST";
export const ADD_LOVESTORY_SUCCESS = "ADD_LOVESTORY_SUCCESS";
export const ADD_LOVESTORY_FAIL = "ADD_LOVESTORY_FAIL";
export const ADD_LOVESTORY_RESET = "ADD_LOVESTORY_RESET";

export const DELETE_LOVESTORY_REQUEST = "DELETE_LOVESTORY_REQUEST";
export const DELETE_LOVESTORY_SUCCESS = "DELETE_LOVESTORY_SUCCESS";
export const DELETE_LOVESTORY_FAIL = "DELETE_LOVESTORY_FAIL";
export const DELETE_LOVESTORY_RESET = "DELETE_LOVESTORY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
