export const SERVICETYPE_DETAILS_REQUEST = "SERVICETYPE_DETAILS_REQUEST";
export const SERVICETYPE_DETAILS_SUCCESS = "SERVICETYPE_DETAILS_SUCCESS";
export const SERVICETYPE_DETAILS_FAIL = "SERVICETYPE_DETAILS_FAIL";

export const ADD_SERVICETYPE_REQUEST = "ADD_SERVICETYPE_REQUEST";
export const ADD_SERVICETYPE_SUCCESS = "ADD_SERVICETYPE_SUCCESS";
export const ADD_SERVICETYPE_FAIL = "ADD_SERVICETYPE_FAIL";
export const ADD_SERVICETYPE_RESET = "ADD_SERVICETYPE_RESET";

export const UPDATE_SERVICETYPE_REQUEST = "UPDATE_SERVICETYPE_REQUEST";
export const UPDATE_SERVICETYPE_SUCCESS = "UPDATE_SERVICETYPE_SUCCESS";
export const UPDATE_SERVICETYPE_FAIL = "UPDATE_SERVICETYPE_FAIL";
export const UPDATE_SERVICETYPE_RESET = "UPDATE_SERVICETYPE_RESET";

export const DELETE_SERVICETYPE_REQUEST = "DELETE_SERVICETYPE_REQUEST";
export const DELETE_SERVICETYPE_SUCCESS = "DELETE_SERVICETYPE_SUCCESS";
export const DELETE_SERVICETYPE_FAIL = "DELETE_SERVICETYPE_FAIL";
export const DELETE_SERVICETYPE_RESET = "DELETE_SERVICETYPE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
